Update azure-static-web-apps-calm-sand-0c76ecb10.yml

diff --git a/.github/workflows/azure-static-web-apps-calm-sand-0c76ecb10.yml b/.github/workflows/azure-static-web-apps-calm-sand-0c76ecb10.yml
--- a/.github/workflows/azure-static-web-apps-calm-sand-0c76ecb10.yml
+++ b/.github/workflows/azure-static-web-apps-calm-sand-0c76ecb10.yml
@@ -22,3 +22,52 @@ jobs:
 
       - name: Set up Node.js 20
         uses: actions/setup-node@v3
+        with:
+          node-version: '20.x'
+
+      - name: Install dependencies
+        run: |
+          cd client
+          npm install
+
+      - name: Build the application
+        run: |
+          cd client
+          CI=false npm run build
+
+      - name: List files in build directory
+        run: |
+          ls -la client/build
+
+      - name: Check for index.html in build directory
+        run: |
+          if [ -f "client/build/index.html" ]; then
+            echo "index.html found in build directory"
+          else
+            echo "index.html not found in build directory"
+            exit 1
+          fi
+
+      - name: Build And Deploy
+        id: builddeploy
+        uses: Azure/static-web-apps-deploy@v1
+        with:
+          azure_static_web_apps_api_token: "c366d59e901a0863dd24b616ced08ffdd2c1be012c74b925e7185c23a7e3a9e65-135232a9-2300-4b2e-9d06-2ea335ab6c6c010440820" # Replace with your actual deployment token
+          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
+          action: "upload"
+          app_location: "client" # App source code path
+          api_location: "api" # Api source code path - optional
+          output_location: "client/build" # Built app content directory
+          skip_app_build: true
+
+  close_pull_request_job:
+    if: github.event_name == 'pull_request' && github.event.action == 'closed'
+    runs-on: ubuntu-latest
+    name: Close Pull Request Job
+    steps:
+      - name: Close Pull Request
+        id: closepullrequest
+        uses: Azure/static-web-apps-deploy@v1
+        with:
+          azure_static_web_apps_api_token: "YOUR_DEPLOYMENT_TOKEN" # Replace with your actual deployment token
+          action: "close"
